
LAMBDA_VERSION = 0
ALPHA_VERSION = LAMBDA_VERSION + 1
BETA_VERSION = LAMBDA_VERSION + 2
GAMMA_VERSION = LAMBDA_VERSION + 3
OMEGA_VERSION = LAMBDA_VERSION + 4

ID_TEMPLATE = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
