import math

CURRENT_VERSION = 0

INITIAL_VERSION = 0
DEV_VERSION = CURRENT_VERSION
DEMO_VERSION = CURRENT_VERSION + 1
FINAL_VERSION = CURRENT_VERSION + 2

PI = math.pi
EARTH_GRAVITY = 9.81  # m/s²
ELECTRON_CHARGE = 1.602e-19  # C

