
DATA_CACHE = "data/golden_goose_data/market_data"
TEST_TICKERS = ["AAPL", "MSFT", "GOOGL", "NVDA", "AMZN", "BTC-USD"]


WIDTH, HEIGHT = 1280, 720  # Standard 720p HD
CENTER = WIDTH // 2, HEIGHT // 2
FPS = 60
FONT_SIZE = 18

SIM_SPEED_OPTIONS = [1, 30, 365, 3650]  # days/sec
DEFAULT_SPEED = SIM_SPEED_OPTIONS[1]

SUN_SIZE = 24
