# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstatus.proto\x12\x05prism\"#\n\rStatusRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"5\n\x0eStatusResponse\x12\x13\n\x0bresponse_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2I\n\rStatusService\x12\x38\n\tGetStatus\x12\x14.prism.StatusRequest\x1a\x15.prism.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSREQUEST']._serialized_start=23
  _globals['_STATUSREQUEST']._serialized_end=58
  _globals['_STATUSRESPONSE']._serialized_start=60
  _globals['_STATUSRESPONSE']._serialized_end=113
  _globals['_STATUSSERVICE']._serialized_start=115
  _globals['_STATUSSERVICE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
